export * from "./actor";
export * from "./actorsmovies";
export * from "./approle";
export * from "./appuser";
export * from "./appuserrole";
export * from "./movie";
export * from "./photo";
export * from "./rating";
export * from "./tokenmodel";